site_name: OpenPlotter 4.x.x
use_directory_urls: false
site_dir: build
repo_url: https://github.com/openplotter/docs
copyright: Created by Sailoog, 2024, Pa√Øsos Catalans. 
theme:
  name: readthedocs
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
nav:
  - Welcome to OpenPlotter!: index.md
  - Description:
    - description/what_is_openplotter.md
    - description/features.md
    - description/how_does_it_work.md
    - description/how_to_collaborate.md
  - Getting started: 
    - getting_started/what_do_you_need.md
    - getting_started/downloading.md
    - getting_started/installing.md
    - getting_started/first_steps.md
    - getting_started/get_support.md
  - Network:
    - network/network_app.md
  - Settings:
    - settings/settings_app.md
    - settings/apps.md
    - settings/general.md
    - settings/raspberry.md
  - Signal K Installer:
    - signalk/signalk_app.md
    - signalk/multiplexing.md
  - OpenCPN Installer:
    - opencpn/opencpn_app.md
    - opencpn/skconnection.md
  - Serial:
    - serial/serial_app.md
    - serial/connectingGPS.md
    - serial/cconnectingRS422.md
    - serial/connectingCAN.md
    - serial/connectingdAISy.md
  - CAN Bus:
    - can/can_app.md
    - can/slcand.md
    - can/mcp2515.md
    - can/output.md
  - Dashboards:
    - dashboards/dashboards_app.md
  - Notifications:
    - notifications/notifications_app.md
    - notifications/examples_actions.md
  - IoB:
    - iob/iob_app.md
    - iob/mqtt.md  
    - iob/telegram.md  
    - iob/lorawan.md  
  - Pypilot: 
    - pypilot/pypilot_app.md
    - pypilot/wiring.md
    - pypilot/calibration.md
    - pypilot/imu.md
    - pypilot/autopilot.md
  - I2C:
    - i2c/i2c_app.md
  - GPIO:
    - gpio/gpio_app.md
    - gpio/1w.md  
    - gpio/digital.md  
    - gpio/pulses.md 
    - gpio/seatalk.md  
  - Maiana AIS Transponder: 
    - maiana/maiana_app.md
    - maiana/connecting.md
    - maiana/configuring.md
  - AvNav Installer:
    - avnav/avnav_app.md
  - SDR VHF:
    - sdr-vhf/sdr-vhf_app.md
  - Moitessier HAT (Hacked):
    - moitessier/moitessier_app.md